import Mathlib.Tactic
-- Suppose G is a group
example (G : Type) [Group G]
-- G has no proper nontrivial subgroups
(h : ∀ H : Subgroup G, H = ⊥ ∨ H = ⊤) :
-- Prove that G is cyclic
IsCyclic G := by
  -- To prove there exists a ∈ G that G = ⟨a⟩
  constructor
    -- Split the cases on whether G is nontrivial or not
  · by_cases hg : Nontrivial G
      -- If G is nontrivial, prove by contradiction
    · by_contra h'
      push_neg at h'
      -- Since G is nontrivial, G has an element a distinct from 1
      have exist_not_one : ∃ a : G, a ≠ 1 := exists_ne 1
      rcases exist_not_one with ⟨a, ha⟩
      -- By assumption, ⟨a⟩ as a subgroup of G is either trivial or G itself
      have : Subgroup.zpowers a = ⊥ ∨ Subgroup.zpowers a = ⊤ := h (Subgroup.zpowers a)
      rcases this with h₀ | h₀
        -- If ⟨a⟩ is trivial, then a = 1, leading to contradiction
      · simp at h₀; contradiction
        -- If ⟨a⟩ is nontrivial, since by assumption G is not cyclic, there exists x ∈ G while x ∉ ⟨a⟩
      · absurd (h' a); push_neg
        -- By assumption nontrivial ⟨a⟩ is G itself
        rw [h₀]
        -- x ∈ G but x ∉ ⟨a⟩ lead to contradiction
        exact fun x => trivial
      -- If G is trivial
    · rw [nontrivial_iff] at hg
      push_neg at hg
      -- G only have element 1
      have : ∀ x : G, x = 1 := by exact fun x => hg x 1
      -- Thus G is a cyclic group generated by 1
      use 1
      exact fun x =>
        Exists.intro (Int.ofNat Nat.zero) (hg ((fun x => 1 ^ x) (Int.ofNat Nat.zero)) x)
